yoav - discretize
GreenBlitz/GB-Robot-Template pull request #146
Opened 2024-05-17 20:00 UTC by YHerm

2024-05-18 11:01 UTC, YoniKiriaty approved these changes

2024-05-18 14:33 UTC, ItayKauff commented
code sucks
gg stands for get good

2024-05-18 14:34 UTC, ItayKauff commented on src/main/java/frc/robot/subsystems/swerve/Swerve.java
> -        return ChassisSpeeds.discretize(chassisSpeeds, RoborioUtils.getCurrentRoborioCycleTime());
y delete
looks good

2024-05-18 14:34 UTC, ItayKauff commented on src/main/java/frc/robot/subsystems/swerve/Swerve.java
> +        double driveMagnitude = Math.sqrt(Math.pow(current.vxMetersPerSecond, 2) + Math.pow(current.vyMetersPerSecond, 2));
stop speaking magic words magic man

2024-05-18 14:39 UTC, ItayKauff requested changes

2024-05-18 14:39 UTC, ItayKauff commented on src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
> +    //todo - why when increasing max on run gets higher
please use fortnite terms

2024-06-02 13:25 UTC, YoniKiriaty submitted a review, later dismissed

2024-06-27 20:59 UTC, closed without merging