Configs Applier -> master
GreenBlitz/GB-Robot-Template pull request #254
Opened 2024-07-24 15:47 UTC by greenblitz4590

2024-07-24 16:12 UTC, bossyshrimp68 reviewed
re-request review when name is fixed

2024-07-28 13:27 UTC, bossyshrimp68 requested changes

2024-07-28 13:27 UTC, bossyshrimp68 commented on src/main/java/frc/utils/ctre/PhoenixProUtils.java
> +    public static boolean checkAndRetry(Supplier<StatusCode> statusCodeSupplier, int tries){
```suggestion
    public static boolean checkAndRetry(Supplier<StatusCode> statusCodeSupplier, int numberOfTries){
```

2024-07-28 14:25 UTC, bossyshrimp68 approved these changes
good job!!

2024-07-28 21:48 UTC, tnrz135 requested changes

2024-07-28 21:48 UTC, tnrz135 commented on src/main/java/frc/utils/ctre/PhoenixProUtils.java
> +    public static boolean checkAndRetry(Supplier<StatusCode> statusCodeSupplier, int numberOfTries) {
This function name suggests it has  2 responsibilities, as it has "and" in its name, which is also not very clean and breaks the Single Responsibility Principle. But actually this function does only one thing and that is the retries. Consider a better name for the function.

2024-08-07 12:49 UTC, bossyshrimp68 approved these changes

2024-08-07 12:52 UTC, merged