Retry status code -> swerve
GreenBlitz/GB-Robot-Template pull request #284
Opened 2024-08-07 16:33 UTC by hillelv

2024-08-07 17:25 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/swerve/gyro/pigeon2/Pigeon2GyroConstants.java
> +	protected static final int NUMBER_OF_STATUS_CODE_RETRIES = 10;
put in pigeon2gyro

2024-08-07 17:26 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/swerve/gyro/pigeon2/Pigeon2GyroConstants.java
> +	protected static final int NUMBER_OF_STATUS_CODE_RETRIES = 10;
```suggestion
	protected static final int APPLY_CONFIG_RETRIES = 10;
```

2024-08-07 19:08 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/encoder/cancoder/CancoderEncoder.java
remove this line (the space line)

2024-08-08 13:59 UTC, YHerm requested changes

2024-08-08 13:59 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/drive/DriveRealConstants.java
> +				logPathPrefix + "FRONT_RIGHT/Drive/",
put the "Drive/" in drive constants and use it in moduleinputs container

2024-08-08 13:59 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerRealConstants.java
> +			logPathPrefix + "FRONT_LEFT/Steer/",
put the "Steer/" in drive constants and use it in moduleinputs container

2024-08-08 13:59 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/drive/DriveRealConstants.java
> +				logPathPrefix + "BACK_LEFT/Drive/",
make all tabs consistent

2024-08-08 13:59 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerRealConstants.java
tabs here too

2024-08-08 13:59 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/gyro/pigeon2/Pigeon2Gyro.java
> +			Logger.recordOutput(LogPaths.ALERT_LOG_PATH + logPath + "ConfigurationFailAt", Timer.getFPGATimestamp());
use {}

2024-08-08 13:59 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/drive/talonfx/TalonFXDriveConfigObject.java
> +		this.logPath = logPathPrefix + "ConfigObject/";
no need  "ConfigObject/" because i want to know which module and what fail and it doesnt give more information

2024-08-08 13:59 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/encoder/cancoder/CancoderEncoder.java
> +			Logger.recordOutput(logPath + "ConfigurationFailAt", Timer.getFPGATimestamp());
use {}

2024-08-12 18:14 UTC, YHerm requested changes

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/drive/DriveRealConstants.java
> +			logPathPrefix + "FRONT_LEFT/",
use module postion instead of pure string

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerRealConstants.java
> +			logPathPrefix + "FRONT_LEFT/",
same here use module postions

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/drive/talonfx/TalonFXDriveConfigObject.java
> +	protected TalonFXDriveConfigObject(String logPath, CTREDeviceID motorID, boolean inverted, TalonFXConfiguration configuration) {
get log path last in constructor

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/drive/talonfx/TalonFXDriveConfigObject.java
> +		this.logPath = logPath;
save it last

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/drive/talonfx/TalonFXDriveConstants.java
> +	public static final String LOG_PATH_ADDITION = "Drive/";
also dont put protected just do static

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/encoder/cancoder/CancoderEncoder.java
> +	private final String logPath;
put it as last member line in gyro

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/encoder/cancoder/CancoderEncoder.java
> +		this.logPath = logPathPrefix + CancoderEncoderConstants.LOG_PATH_ADDITION;
set it last

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/encoder/cancoder/CancoderEncoderConstants.java
> +    protected static final int APPLY_CONFIG_RETRIES = 10;
dont use protected in const file just static

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/steer/talonfx/TalonFXSteerConfigObject.java
> +	private final String logPath;
last member

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/steer/talonfx/TalonFXSteerConfigObject.java
> +        this.logPath = logPath;
set it last

2024-08-12 18:14 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/steer/talonfx/TalonFXSteerConstants.java
>  	protected static final int NO_ENCODER_ID = -1;
static

2024-08-12 21:39 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/modules/steer/talonfx/TalonFXSteerConstants.java
>  	protected static final int NO_ENCODER_ID = -1;
same here

2024-08-13 08:17 UTC, YHerm requested changes
Do spotlessApply, there are a lot of long lines. If spotless do weird format you can do:
//@format::off
my code
//@format::on
and format yourself

2024-08-13 11:56 UTC, hillelv commented
>  do: //@Format::off my code //@Format::on 

bruh that's the wrong syntax in _so many ways_, it's almost **impressive**

2024-08-13 12:20 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerFactory.java
> +							SteerRealConstants.BACK_LEFT_CONSTANTS(SwerveName.SWERVE.getLogPath() + ModuleConstants.LOG_PATH_ADDITION)
one tab less like the others

2024-08-13 12:23 UTC, YHerm requested changes
After that test in sim all logs are fine. Then i can check today or tomorrow the apply log on robot and merge

2024-08-13 12:51 UTC, hillelv commented
the logs look good

2024-08-14 18:30 UTC, greenblitz4590 submitted a review, later dismissed

2024-08-15 12:40 UTC, YHerm requested changes
spotless after finish comments

2024-08-15 12:40 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/drive/DriveFactory.java
> +					);
make one line

2024-08-15 12:40 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerFactory.java
> +				// @formatter:on
delete // @formatter:off // @formatter:on

2024-08-15 14:09 UTC, YHerm reviewed
Letting you know. The code working, but there is a problem that unrelated to this project that making this not work because the order of creation. So it's need the state handler to get merge first

2024-08-20 09:51 UTC, YHerm approved these changes

2024-08-21 17:37 UTC, merged