Power Distribution Device ID -> core
GreenBlitz/GB-Robot-Template pull request #336
Opened 2024-09-05 14:55 UTC by drorta

2024-09-05 14:59 UTC, YHerm requested changes

2024-09-05 14:59 UTC, YHerm commented on src/main/java/frc/utils/battery/BatteryConstants.java
> +	);
put in class ID's

2024-09-05 14:59 UTC, YHerm commented on src/main/java/frc/utils/battery/PowerDistributionDeviceID.java
> +}
consider making it a record

2024-09-05 15:00 UTC, drorta commented on src/main/java/frc/utils/battery/BatteryConstants.java
> +	);
k

2024-09-05 15:26 UTC, YHerm commented on src/main/java/frc/utils/battery/PowerDistributionDeviceID.java
> +}
kind of class

2024-09-05 16:21 UTC, GilStein1 submitted a review, later dismissed
very good👌

2024-09-05 18:06 UTC, YHerm commented on src/main/java/frc/utils/battery/BatteryConstants.java
> +	protected static final PowerDistribution.ModuleType DEFAULT_MODULE_TYPE = PowerDistribution.ModuleType.kRev;
no need default

2024-09-05 18:06 UTC, YHerm commented on src/main/java/frc/utils/battery/PowerDistributionDeviceID.java
> +public record PowerDistributionDeviceID(int id, PowerDistribution.ModuleType type) {
```suggestion
public record PowerDistributionDeviceID(int ID, PowerDistribution.ModuleType type) {
```

2024-09-05 18:06 UTC, YHerm commented on src/main/java/frc/utils/battery/PowerDistributionDeviceID.java
> +	}
remove

2024-09-05 18:07 UTC, YHerm commented on src/main/java/frc/utils/battery/BatteryUtils.java
> +import static frc.robot.constants.IDs.*;
dont use *

2024-09-06 14:31 UTC, YHerm approved these changes

2024-09-06 16:00 UTC, YHerm approved these changes

2024-09-08 14:53 UTC, YoniKiriaty submitted a review, later dismissed

2024-09-08 16:24 UTC, YHerm approved these changes

2024-09-08 16:24 UTC, Sh-Pe approved these changes

2024-09-08 16:42 UTC, GilStein1 approved these changes
Very good👌

2024-09-08 16:57 UTC, maya1414 approved these changes

2024-09-08 17:32 UTC, greenblitz4590 approved these changes

2024-09-08 17:32 UTC, merged