Request, PhoenixRequest -> core
GreenBlitz/GB-Robot-Template pull request #350
Opened 2024-09-10 16:12 UTC by YHerm

2024-09-10 16:28 UTC, hillelv reviewed
do same orders for withSetPoint and getControlRequest in both classes

2024-09-10 16:52 UTC, drorta commented on src/main/java/frc/robot/hardware/request/phoenix6/Phoenix6AngleRequest.java
> +
lol

2024-09-10 16:54 UTC, drorta approved these changes
gg

2024-09-10 16:56 UTC, hillelv submitted a review, later dismissed

2024-09-10 16:58 UTC, YoniKiriaty submitted a review, later dismissed

2024-09-11 10:06 UTC, bossyshrimp68 requested changes

2024-09-11 11:09 UTC, merged