Sparkmaxes -> core
GreenBlitz/GB-Robot-Template pull request #375
Opened 2024-09-25 09:50 UTC by greenblitz4590

all the sparkmax motor with all things

2024-09-25 13:50 UTC, drorta requested changes

2024-09-25 13:50 UTC, drorta commented on src/main/java/frc/robot/hardware/motor/cansparkmax/SparkMaxMotor.java
> +
❤️

2024-09-25 13:50 UTC, drorta commented on src/main/java/frc/robot/hardware/motor/phoenix6/TalonFXMotor.java
> +
❤️

2024-09-25 13:50 UTC, drorta commented on src/main/java/frc/robot/hardware/motor/phoenix6/TalonFXMotor.java
> +
❤️

2024-09-25 14:49 UTC, greenblitz4590 commented on src/main/java/frc/robot/hardware/motor/cansparkmax/BrushedSparkMAXMotor.java
> +	protected final CANSparkMax motor;
private

2024-09-25 14:51 UTC, NoamRosenberg08 requested changes

2024-09-25 14:51 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/hardware/motor/cansparkmax/SparkMaxMotor.java
> +		connectedInput.connected = motor.getBusVoltage() > 0;
add logger.process input(...,connected)

2024-09-25 14:51 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxDoubleSignal.java
> +    Supplier<Double> doubleSignalSupplier;
private final

2024-09-25 14:55 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/SparkMaxMotor.java
> +	protected final String logPath;
privatw

2024-09-25 14:56 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/SparkMaxMotor.java
> +		connectedInput = new ConnectedInputAutoLogged();
this.

2024-09-25 14:56 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/SparkMaxMotor.java
> +	public SparkMaxMotor(CANSparkMax motor, String logPath) {
logpath first

2024-09-25 16:05 UTC, hillelv submitted a review, later dismissed

2024-09-25 17:22 UTC, bossyshrimp68 requested changes

2024-09-25 17:22 UTC, bossyshrimp68 commented on src/main/java/frc/robot/hardware/motor/cansparkmax/SparkMaxMotor.java
> +		AlertManager.addAlert(new PeriodicAlert(Alert.AlertType.WARNING, logPath + "disconnectedAt", () -> !isConnected()));
why is this a warning

2024-09-25 19:07 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/phoenix6/TalonFXMotor.java
> -
return this

2024-09-25 19:07 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/phoenix6/TalonFXMotor.java
> -
this tooo

2024-09-25 19:07 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxAngleSignal.java
> +		return angleSignalSupplier.get();
add timestamp

2024-09-25 19:07 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxDoubleSignal.java
> +		return doubleSignalSupplier.get();
here toooo

2024-09-25 19:08 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxDoubleSignal.java
> +	private final Supplier<Double> doubleSignalSupplier;
```suggestion
	private final Supplier<Double> valueSupplier;
```

2024-09-25 19:08 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxAngleSignal.java
> +	private final Supplier<Double> angleSignalSupplier;
```suggestion
	private final Supplier<Double> angleSupplier;
```

2024-09-25 19:10 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/BrushedSparkMAXMotor.java
> +			throw new IllegalArgumentException("inserted brushless sparkmax motor to brushed!");
```suggestion
			throw new IllegalArgumentException("inserted BrushlessSparkMAXMotor  to BrushedSparkMAXMotor!");
```

2024-09-25 19:10 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/BrushlessSparkMAXMotor.java
> +	private final BiFunction<Rotation2d, Rotation2d, Rotation2d> feedforward;
remove ff

2024-09-25 19:11 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/BrushlessSparkMAXMotor.java
> +			throw new IllegalArgumentException("inserted brushed sparkmax motor to brushless!");
like in the the before

2024-09-25 19:12 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/SparkMaxMotor.java
> +	}
put this above the other overrides

2024-09-25 19:12 UTC, YHerm requested changes
do gradlew SpotlessAPPLY

2024-09-25 22:08 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/BrushlessSparkMAXMotor.java
Move spark max wrapper and device is to here

2024-09-25 22:09 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/cansparkmax/BrushlessSparkMAXMotor.java
I think the pack name can be just spark or rev

2024-09-25 22:15 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxDoubleSignal.java
> +		return new TimedValue<>(valueSupplier.get(), System.currentTimeMillis());
Why system and not timer or Halutil or logger?

2024-09-25 22:15 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxDoubleSignal.java
> +		return new TimedValue<>(valueSupplier.get(), System.currentTimeMillis());
If the talonfx return like system keep it

2024-09-25 22:15 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxAngleSignal.java
> +		return new TimedValue<>(valueSupplier.get(), System.currentTimeMillis());
Here too

2024-09-26 07:12 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/sparkmax/BrushedSparkMAXMotor.java
> +			throw new IllegalArgumentException("\"inserted BrushlessSparkMAXMotor to BrushedSparkMAXMotor!\"");
Why the “/“

2024-09-26 07:12 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/sparkmax/BrushlessSparkMAXMotor.java
> +			throw new IllegalArgumentException("\"inserted BrushedSparkMAXMotor to BrushlessSparkMAXMotor!\"");
Why the “/“

2024-09-26 07:14 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxAngleSignal.java
> +
angle supplier

2024-09-26 07:21 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxDoubleSignal.java
> +		return new TimedValue<>(valueSupplier.get(), HALUtil.getHALRuntimeType());
Runtime type?

2024-09-26 07:21 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxDoubleSignal.java
> +	public SparkMaxDoubleSignal(String name, Supplier<Double> doubleSignalSupplier) {
```suggestion
	public SparkMaxDoubleSignal(String name, Supplier<Double> valueSupplier) {
```

2024-09-26 07:39 UTC, YHerm requested changes

2024-09-26 07:39 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxAngleSignal.java
> +	public SparkMaxAngleSignal(String name, Supplier<Double> angleSignalSupplier, AngleUnit angleUnit) {
```suggestion
	public SparkMaxAngleSignal(String name, Supplier<Double> angleSupplier, AngleUnit angleUnit) {
```

2024-09-26 07:39 UTC, YHerm commented on src/main/java/frc/robot/hardware/motor/sparkmax/SparkMaxMotor.java
> +	private final CANSparkMax motor;
Make protected instead of 2 pointers

2024-09-26 11:53 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxAngleSignal.java
> +		return new TimedValue<>(valueSupplier.get(), HALUtil.getHALRuntimeType());
runtime type?

2024-09-26 14:51 UTC, bossyshrimp68 submitted a review, later dismissed

2024-09-26 15:08 UTC, merged