PoseEstimator interfacing with outer classes
GreenBlitz/GB-Robot-Template pull request #466
Opened 2024-11-19 22:31 UTC by Sh-Pe

2024-11-19 22:32 UTC, Sh-Pe commented
no need to test since it's just interfacing

2024-11-20 17:08 UTC, Yotam7 approved these changes
Top Google result for gyro(used here in `gyroAngle`), we need to have a talk about shortening names
![image](https://github.com/user-attachments/assets/370b806e-6f8a-4cd7-8bff-490187a3c269)

2024-11-20 17:23 UTC, bossyshrimp68 approved these changes

2024-11-20 17:47 UTC, emilyyyylime requested changes

2024-11-20 17:47 UTC, emilyyyylime commented on src/main/java/frc/robot/poseestimator/IOdometryEstimator.java
> +	void updateOdometry(OdometryObservation[] odometryObservation);
```suggestion
	void updateOdometry(OdometryObservation[] odometryObservations);
```

2024-11-20 17:47 UTC, emilyyyylime commented on src/main/java/frc/robot/poseestimator/IPoseEstimator.java
> +	Pose2d getEstimatedPoseAtTimeStamp(double timeStamp);
Timestamp is usually one word 
```suggestion
	Pose2d getEstimatedPoseAtTimestamp(double timestamp);
```

2024-11-20 17:47 UTC, emilyyyylime commented on src/main/java/frc/robot/poseestimator/observations/OdometryObservation.java
> +public record OdometryObservation(SwerveModulePosition[] wheelsPositions, Rotation2d gyroAngle, double timestamp) {}
```suggestion
public record OdometryObservation(SwerveModulePosition[] wheelPositions, Rotation2d gyroAngle, double timestamp) {}
```

2024-11-20 17:47 UTC, emilyyyylime commented on src/main/java/frc/robot/poseestimator/IPoseEstimator.java
> +	Pose2d getEstimatedPoseAtTimeStamp(double timeStamp);
In fact you used this same spelling in other files; so this is more consistent too

2024-11-20 18:12 UTC, emilyyyylime approved these changes

2024-11-20 20:26 UTC, drorta submitted a review, later dismissed

2024-11-20 20:37 UTC, GilStein1 commented on src/main/java/frc/robot/poseestimator/IOdometryEstimator.java
> +	void resetOdometry(SwerveModulePosition[] wheelPositions, Rotation2d gyroAngle, Pose2d robotPose);
2 different things, gyro might not be reset so its' rotation and the odometryPoses' rotation are not equal

2024-11-20 20:38 UTC, GilStein1 commented on src/main/java/frc/robot/poseestimator/IOdometryEstimator.java
> +	void resetHeadingOffset(Rotation2d newHeading);
new heading, the offset is calculated from the new robotHeading

2024-11-21 08:36 UTC, emilyyyylime commented on src/main/java/frc/robot/poseestimator/IOdometryEstimator.java
> +	void resetOdometry(SwerveModulePosition[] wheelPositions, Rotation2d gyroAngle, Pose2d robotPose);
apostrphe's :3

2024-11-21 08:36 UTC, emilyyyylime commented on src/main/java/frc/robot/poseestimator/IOdometryEstimator.java
> +	void calculateHeadingOffsetFromRobotHeading(Rotation2d newHeading);
How about `setHeading`? I don't think it's that relevant for the callers of this function to know how it does what it does

2024-11-21 10:20 UTC, drorta approved these changes

2024-11-21 12:04 UTC, GilStein1 approved these changes
approve from Shahar (he opened the PR for me and now can't comment, he didn't write this code)

2024-11-21 13:29 UTC, hillelv approved these changes

2024-11-21 13:31 UTC, emilyyyylime approved these changes

2024-11-21 15:54 UTC, aaa-png approved these changes

2024-11-22 21:03 UTC, bossyshrimp68 approved these changes

2024-11-22 21:34 UTC, merged