Make MechanismSimulation an Interface -> core
GreenBlitz/GB-Robot-Template pull request #477
Opened 2024-11-28 08:52 UTC by drorta

2024-11-28 09:14 UTC, hillelv commented on src/main/java/frc/robot/hardware/mechanisms/SimpleMotorSimulation.java
> +		return gearRatio;
DCMotorSim has a gear ratio getter

2024-11-28 09:38 UTC, Nitay4 submitted a review, later dismissed

2024-11-28 11:36 UTC, Sh-Pe commented on src/main/java/frc/robot/hardware/mechanisms/MechanismSimulation.java
> +	Rotation2d getRotorVelocityAnglesPerSecond();
angles per seconds? Maybe rotation2d per seconds. Angles are not units, but seconds are. It physically doesn't work. 

Also, angles should be in singular and not plural. @YHerm

2024-11-28 11:36 UTC, Sh-Pe commented on src/main/java/frc/robot/hardware/mechanisms/MechanismSimulation.java
> +	void setInputVoltage(double voltage);
this just doesn't make sense. If we need to specify that velocity are in Rotation2d/sec, why isn't it VoltageVolt? 

ik this problematic naming occurs outside to this PR. But I wouldn't want to approve inconsistent code.

2024-11-28 13:33 UTC, hillelv requested changes
do better

2024-11-28 19:48 UTC, YHerm commented on src/main/java/frc/robot/hardware/mechanisms/MechanismSimulation.java
remove space

2024-11-28 19:51 UTC, YHerm requested changes

2024-11-28 19:51 UTC, YHerm commented on src/main/java/frc/robot/hardware/mechanisms/MechanismSimulation.java
> +	double getGearRatio();
why?

2024-11-28 19:51 UTC, YHerm commented on src/main/java/frc/robot/hardware/mechanisms/MechanismSimulation.java
> +	double getGearRatio();
*why u need the function

2024-11-28 21:10 UTC, YHerm commented on src/main/java/frc/robot/hardware/mechanisms/WPIMechanismSimulation.java
put in package with the simple

2024-11-29 15:37 UTC, hillelv commented on src/main/java/frc/robot/hardware/mechanisms/WPIMechanismSimulation.java
> +		this.gearRatio = gearRatio;
why not make it a function like raz wanted?

2024-12-01 15:14 UTC, YoniKiriaty submitted a review, later dismissed

2024-12-01 15:14 UTC, YoniKiriaty commented on src/main/java/frc/robot/hardware/mechanisms/wpi/WPIMechanismSimulation.java
> +
space

2024-12-01 15:21 UTC, YHerm commented on src/main/java/frc/robot/hardware/mechanisms/wpi/WPIMechanismSimulation.java
> +public abstract class WPIMechanismSimulation implements MechanismSimulation {
make it interface with default function

2024-12-01 17:04 UTC, hillelv requested changes
wtf is wpi mechanism????

2024-12-01 18:22 UTC, bossyshrimp68 approved these changes

2024-12-01 18:26 UTC, YoniKiriaty approved these changes

2024-12-01 18:27 UTC, maya1414 approved these changes

2024-12-02 11:11 UTC, hillelv approved these changes

2024-12-02 11:13 UTC, YHerm approved these changes

2024-12-02 11:14 UTC, merged