Refactor TalonFXMotor to use functions -> core
GreenBlitz/GB-Robot-Template pull request #478
Opened 2024-11-28 12:51 UTC by drorta

2024-11-28 13:05 UTC, YHerm requested changes

2024-11-28 13:05 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/motor/TalonFXMotor.java
> +	}
put in talonfx wrapper

2024-11-28 13:05 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/motor/TalonFXMotor.java
> +	private Optional<TalonFXSimulation> createTalonFXSimulationOptional(MechanismSimulation simulation, TalonFXConfiguration configuration) {
```suggestion
	private Optional<TalonFXSimulation> createSimulation(MechanismSimulation simulation, TalonFXConfiguration configuration) {
```

2024-11-28 13:27 UTC, hillelv approved these changes

2024-11-28 19:00 UTC, YHerm approved these changes
make sure its tested

2024-11-28 19:47 UTC, YHerm requested changes

2024-11-28 19:47 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/motor/TalonFXWrapper.java
> +		super(ctreDeviceID.ID(), Robot.ROBOT_TYPE.isSimulation() ? BusChain.ROBORIO.getChainName() : ctreDeviceID.busChain().getChainName());
move to function

2024-11-28 21:09 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/motor/TalonFXWrapper.java
> +import frc.utils.brakestate.BrakeStateManager;
format my G

2024-11-28 21:19 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/motor/TalonFXWrapper.java
> +		return Robot.ROBOT_TYPE.isSimulation() ? BusChain.ROBORIO.getChainName() : ctreDeviceID.busChain().getChainName();
move this to Phoenix6DeviceID

2024-11-29 16:31 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/motor/TalonFXWrapper.java
> +		super(ctreDeviceID.ID(), Phoenix6DeviceID.determineBusChain(ctreDeviceID));
I meant to move also this part to the other class

2024-12-01 15:12 UTC, YoniKiriaty commented on src/main/java/frc/robot/hardware/phoenix6/Phoenix6DeviceID.java
> +		this.busChain = Objects.equals(determineBusChain(busChain), BusChain.CANIVORE.getChainName()) ? BusChain.CANIVORE : BusChain.ROBORIO;
cant you do 
```suggestion
		this.busChain =determineBusChain(busChain).equals(BusChain.CANIVORE.getChainName()) ? BusChain.CANIVORE : BusChain.ROBORIO;
```

2024-12-01 15:13 UTC, drorta commented on src/main/java/frc/robot/hardware/phoenix6/Phoenix6DeviceID.java
> +		this.busChain = Objects.equals(determineBusChain(busChain), BusChain.CANIVORE.getChainName()) ? BusChain.CANIVORE : BusChain.ROBORIO;
```suggestion
		this.busChain = determineBusChain(busChain);
```

2024-12-01 15:16 UTC, YoniKiriaty submitted a review, later dismissed

2024-12-01 15:20 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/Phoenix6DeviceID.java
> +
remove space

2024-12-01 17:08 UTC, hillelv approved these changes

2024-12-01 17:57 UTC, bossyshrimp68 approved these changes

2024-12-01 18:24 UTC, maya1414 approved these changes

2024-12-01 18:25 UTC, YoniKiriaty approved these changes

2024-12-01 19:42 UTC, merged