Phoenix6 IsConnected -> core
GreenBlitz/GB-Robot-Template pull request #493
Opened 2024-12-05 17:43 UTC by drorta

2024-12-05 17:52 UTC, YHerm requested changes
a lot of duplicate code, find a better way

2024-12-06 22:23 UTC, YHerm requested changes

2024-12-06 22:23 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/Phoenix6Device.java
> +	public abstract ParentDevice getDevice();
abstract funcs in bottom of class

2024-12-06 22:23 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/gyro/Pigeon2Gyro.java
> +	public ParentDevice getDevice() {
make it return Pigeon2

2024-12-06 22:23 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/angleencoder/CANCoderEncoder.java
> +	public ParentDevice getDevice() {
make it return cancoder

2024-12-06 22:23 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/motor/TalonFXMotor.java
> +	}
make it return talonfx

2024-12-07 09:29 UTC, YHerm requested changes

2024-12-07 09:29 UTC, YHerm commented on src/main/java/frc/robot/hardware/phoenix6/angleencoder/CANCoderEncoder.java
i'm pretty sure this function already exist in this class (also in the talonfxmotor and pigeon2gyro)

2024-12-08 12:31 UTC, hillelv commented on src/main/java/frc/robot/hardware/phoenix6/gyro/Pigeon2Gyro.java
> +	public Pigeon2 getDevice() {
why not the wrapper? either return wrapper or parent device, no need to choose a class in between

2024-12-16 15:25 UTC, YHerm approved these changes

2024-12-16 15:37 UTC, Nitay4 approved these changes
why so skibidy

2024-12-16 15:54 UTC, hillelv approved these changes

2024-12-16 21:22 UTC, tnrz135 approved these changes

2024-12-17 04:41 UTC, merged