Motor subsystem base -> core
GreenBlitz/GB-Robot-Template pull request #494
Opened 2024-12-05 19:46 UTC by maya1414

2024-12-05 21:19 UTC, hillelv requested changes
I think there should be a subsystem that uses IMotor (maybe abstract) and a class that inherits from it and uses ControllableMotor, there should be a way to create a non-controllable-motor subsystem

2024-12-05 21:19 UTC, hillelv commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorCommandsBuilder.java
> +		return new RunCommand(() -> motorSubsystem.setPower(power), motorSubsystem).withName("set power");
consider adding the amount of power to the name

2024-12-05 21:19 UTC, hillelv commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	String logPath;
GBSubsystem already has log path

2024-12-05 21:19 UTC, hillelv commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	MotorCommandsBuilder motorCommandsBuilder;
why don't you initialize it?

2024-12-05 21:19 UTC, hillelv commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	SysIdCalibrator sysIdCalibrator;
I think they should be protected final

2024-12-05 21:19 UTC, hillelv commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	}
why? no need to duplicate code

2024-12-05 21:22 UTC, hillelv commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	ControllableMotor motor;
you also didn't initialize this

2024-12-06 10:54 UTC, drorta requested changes
I like it, nice start! 🫡

2024-12-06 10:54 UTC, drorta commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	GBSubsystem logPath;
You don't need a GBSubsystem saved

2024-12-06 10:54 UTC, drorta commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	protected final SysIdCalibrator sysIdCalibrator;
Consider making these private final

2024-12-06 10:54 UTC, drorta commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	public MotorSubsystem(GBSubsystem logPath, ControllableMotor motor) {
```suggestion
	public MotorSubsystem(String logPath, ControllableMotor motor) {
```
Doesn't need to be GBSubsystem

2024-12-06 10:54 UTC, drorta commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +		super(String.valueOf(logPath));
```suggestion
		super(logPath);
```
You can just do this if it's a string, you don't need a GBSubsystem

2024-12-06 10:54 UTC, drorta commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	MotorCommandsBuilder motorCommandsBuilder;
you don't initialize this in the constructor

2024-12-06 10:54 UTC, drorta commented on src/main/java/frc/robot/subsystems/motorsubsystem/MotorSubsystem.java
> +	}
You don't need this function, the class your inheriting from (GBSubsystem) already has this

2024-12-07 09:27 UTC, closed without merging