add-relative-functions-to-signals -> core
GreenBlitz/GB-Robot-Template pull request #497
Opened 2024-12-08 15:56 UTC by Nitay4

2024-12-08 17:05 UTC, YHerm requested changes

2024-12-08 17:05 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/AngleSignal.java
> +		return !MathUtil.isNear(value.getRotations(), getLatestValue().getRotations(), distance.getRotations());
use the function isNear from above

2024-12-08 17:05 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/DoubleSignal.java
> +		return !MathUtil.isNear(value, getLatestValue(), distance);
use the function is near from above

2024-12-08 17:05 UTC, YHerm commented on src/main/java/frc/robot/hardware/signal/DoubleSignal.java
> +		return getLatestValue() > value;
switch the sign

2024-12-12 14:23 UTC, YoniKiriaty commented on src/main/java/frc/robot/hardware/signal/AngleSignal.java
> +	}
this is not how math works.
also u want to get value and return if the distnace of current to given value is bigger that given distnace

2024-12-12 22:37 UTC, YHerm requested changes
Please test it in simulation

2024-12-16 14:04 UTC, YoniKiriaty commented on src/main/java/frc/robot/hardware/interfaces/InputSignal.java
> +	boolean isFarBy(T value, T distance);
why `By`? you don't do the same for `isNear`

2024-12-16 14:07 UTC, Yotam7 commented on src/main/java/frc/robot/hardware/interfaces/InputSignal.java
> +	boolean isLess(T value);
```suggestion
	boolean isLessThan(T value);
```

2024-12-16 15:32 UTC, NoamRosenberg08 requested changes

2024-12-16 15:32 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/hardware/signal/DoubleSignal.java
> +	public boolean isFar(Double value, Double distance) {
isFurthur

2024-12-16 15:32 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/hardware/signal/AngleSignal.java
> +	public boolean isFar(Rotation2d value, Rotation2d distance) {
isFurthur

2024-12-16 15:32 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/hardware/signal/AngleSignal.java
> +	public boolean isFar(Rotation2d value, Rotation2d distance) {
isFurthur

2024-12-16 15:39 UTC, NoamRosenberg08 submitted a review, later dismissed

2024-12-16 15:53 UTC, hillelv requested changes

2024-12-16 15:53 UTC, hillelv commented on src/main/java/frc/robot/hardware/interfaces/InputSignal.java
> +	boolean isFurthur(T value, T distance);
furthur? do you mean further?

2024-12-16 15:53 UTC, hillelv commented on src/main/java/frc/robot/hardware/signal/AngleSignal.java
> +	public boolean isFurthur(Rotation2d value, Rotation2d distance) {
```suggestion
	public boolean isFurthur(Rotation2d value, Rotation2d tolerance) {
```

2024-12-16 15:53 UTC, hillelv commented on src/main/java/frc/robot/hardware/signal/DoubleSignal.java
> +	public boolean isFurthur(Double value, Double distance) {
```suggestion
	public boolean isFurthur(Double value, Double tolerance) {
```

2024-12-16 17:06 UTC, hillelv approved these changes

2024-12-17 06:59 UTC, NoamRosenberg08 approved these changes

2024-12-18 14:28 UTC, NoamRosenberg08 approved these changes

2024-12-18 18:08 UTC, DANNA2828 approved these changes
(/*0*)/

2024-12-18 19:28 UTC, NoamRosenberg08 approved these changes

2024-12-18 23:34 UTC, tnrz135 approved these changes

2024-12-19 07:43 UTC, YHerm approved these changes

2024-12-19 07:44 UTC, merged