Names, default ID, magic numbers (core CR) -> core
GreenBlitz/GB-Robot-Template pull request #502
Opened 2024-12-09 15:14 UTC by drorta

2024-12-09 15:35 UTC, NoamRosenberg08 requested changes

2024-12-09 15:35 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/constants/IDs.java
> +		-1,
Change to 0, might throw exceptioj

2024-12-09 15:38 UTC, NoamRosenberg08 approved these changes

2024-12-09 15:44 UTC, tnrz135 approved these changes

2024-12-09 15:56 UTC, hillelv approved these changes

2024-12-09 17:07 UTC, YHerm requested changes

2024-12-09 17:24 UTC, itamaroryan approved these changes

2024-12-09 20:36 UTC, Yotam7 approved these changes

2024-12-09 21:38 UTC, tnrz135 approved these changes

2024-12-10 09:23 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/constants/IDs.java
>  		PowerDistribution.ModuleType.kRev
We can either make it a negative number, thus throwing an exception


Or make a json file with all the constants

2024-12-10 14:48 UTC, YHerm approved these changes

2024-12-10 14:48 UTC, merged