duty cycle request -> master
GreenBlitz/GB-Robot-Template pull request #529
Opened 2024-12-22 13:40 UTC by maya1414

2024-12-22 13:42 UTC, Nitay4 submitted a review, later dismissed

2024-12-22 13:42 UTC, Nitay4 commented on src/main/java/frc/robot/hardware/phoenix6/request/Phoenix6RequestBuilder.java
> +	public static Phoenix6Request<Double> build(DutyCycleOut dutyCycle) {
```suggestion
	public static Phoenix6Request<Double> build(DutyCycleOut dutyCycleOut) {
```

2024-12-22 13:57 UTC, YoniKiriaty submitted a review, later dismissed

2024-12-22 14:02 UTC, Nitay4 submitted a review, later dismissed
why so skibidy

2024-12-22 14:16 UTC, YoniKiriaty commented on src/main/java/frc/robot/hardware/phoenix6/request/Phoenix6RequestBuilder.java
> +import com.ctre.phoenix6.controls.*;
import all dont use *

2024-12-22 17:08 UTC, drorta requested changes

2024-12-22 17:08 UTC, drorta commented on src/main/java/frc/robot/hardware/phoenix6/request/Phoenix6RequestBuilder.java
I think you should also remove setPower everywhere its relevant, talk to @YHerm herman about that

2024-12-23 15:08 UTC, NoamRosenberg08 submitted a review, later dismissed

2024-12-23 17:59 UTC, hillelv approved these changes

2024-12-23 18:28 UTC, TheOnion313 requested changes

2024-12-23 18:28 UTC, TheOnion313 commented on src/main/java/frc/robot/hardware/phoenix6/motor/TalonFXMotor.java
> -
This needs a replacement in the interface to ensure all motors support setting their power and stopping them

2024-12-30 11:17 UTC, closed without merging