Better currentCommand subsystem logging
GreenBlitz/GB-Robot-Template pull request #532
Opened 2024-12-23 07:31 UTC by drorta

2024-12-23 13:14 UTC, YoniKiriaty submitted a review, later dismissed

2024-12-23 13:14 UTC, YoniKiriaty commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> -
make a function that takes a command and automatically updates the current command name variable.
additionally the variable needs to be a private variable in GBSubsystem and should have this function returning it.

2024-12-23 13:43 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +		);
use command.before()

2024-12-23 13:43 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +	}
remove

2024-12-23 13:44 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +		);
but it doesnt solve the problem if u still use command.getName(). the purpose of the projects to not use it

2024-12-23 15:15 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +	}
consider renaming to 
withCommand(Command)

2024-12-23 15:31 UTC, YHerm requested changes

2024-12-23 15:31 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +		this.currentCommand = new InstantCommand().withName("No Command");
```suggestion
		this.currentCommand = new InstantCommand().withName("None");
```

2024-12-23 15:31 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +		);
use commad.before

2024-12-23 15:31 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +	protected Command withSetCurrentCommand(Command command){
```suggestion
	protected Command applyToSubsystem(Command command){
```
```suggestion
	protected Command asSubsystemCommand(Command command){
```
some like this,

2024-12-23 15:31 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +	protected Command withSetCurrentCommand(Command command){
why protected?

2024-12-23 15:31 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +	protected Command withSetCurrentCommand(Command command){
get name as param

2024-12-23 17:43 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +		return command.beforeStarting(new InstantCommand(() -> currentCommand = command));
add require

2024-12-23 18:29 UTC, YHerm requested changes

2024-12-23 18:29 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +		return this.currentCommand.withName(commandName);
U need to get also command

2024-12-24 17:25 UTC, YHerm requested changes

2024-12-24 17:25 UTC, YHerm commented on src/main/java/frc/robot/subsystems/GBSubsystem.java
> +		this.currentCommand = Commands.none().withName("No command is currently running on the subsystem");
Just write None, it's too long

2024-12-24 18:46 UTC, YHerm approved these changes
Make sure its tested!

2024-12-24 18:47 UTC, hillelv approved these changes

2024-12-24 18:57 UTC, tnrz135 approved these changes

2024-12-24 19:05 UTC, Nitay4 approved these changes

2024-12-24 19:07 UTC, merged