Update REVLib -> master
GreenBlitz/GB-Robot-Template pull request #538
Opened 2024-12-26 17:09 UTC by drorta

2024-12-27 20:44 UTC, YHerm commented on src/main/java/frc/robot/hardware/rev/motors/BrushedSparkMAXMotor.java
pick the name of the package: motors or motor and change in rev and phoenix6

2024-12-28 11:28 UTC, YHerm commented on src/main/java/frc/robot/hardware/rev/motors/SparkMaxMotor.java
> +
no need space

2024-12-28 11:28 UTC, YHerm commented on src/main/java/frc/robot/hardware/rev/motors/SparkMaxWrapper.java
> +
no need space

2024-12-28 19:04 UTC, tnrz135 requested changes

2024-12-28 19:04 UTC, tnrz135 commented on src/main/java/frc/robot/hardware/rev/motors/SparkMaxMotor.java
> +		// TODO motor.configure()
TODO?

2024-12-28 19:05 UTC, drorta commented on src/main/java/frc/robot/hardware/rev/motors/SparkMaxMotor.java
> +		// TODO motor.configure()
https://github.com/GreenBlitz/GB-Robot-Template/pull/543

2024-12-29 11:01 UTC, NoamRosenberg08 requested changes

2024-12-29 11:01 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/hardware/phoenix6/motors/TalonFXMotor.java
> +package frc.robot.hardware.phoenix6.motors;
if its a REVLib change, why does the Phoenix6 Lib is also changed?

2024-12-29 14:39 UTC, GilStein1 approved these changes
//todo fix

2024-12-29 14:46 UTC, YHerm approved these changes

2024-12-29 15:17 UTC, hillelv approved these changes

2024-12-31 08:11 UTC, yonnbro approved these changes

2024-12-31 08:47 UTC, merged